#!/bin/bash

set -e

cid="${1}"

if [[ -z "${cid}" ]] ; then
  echo 'Usage: unregister-container CONTAINER_ID'
  exit 1
fi

rm -f "/etc/nginx/sites-enabled/${cid}.*.conf"
sed -i "s|^.* # CID: ${cid}$||" /tmp/etc-hosts.partial
